{
 "title": "p26",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SystemInfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU",
   "type": "graph",
   "description": "nval02:cpu:16core, memory:16G\nnval03:cpu:16core, memory:16G",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu(nval02)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "cpu(nval03)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "System Memory ",
   "type": "graph",
   "description": "nval02:cpu:16core, memory:16G\nnval03:cpu:16core, memory:16G",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mem(nval02)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "mem(nval03)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "System/CPU/Memory(nval02)",
   "type": "graph",
   "description": "nval02:cpu:16core, memory:16G\nnval03:cpu:16core, memory:16G",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system-cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "system-memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "System/CPU/Memory(nval03)",
   "type": "graph",
   "description": "nval02:cpu:16core, memory:16G\nnval03:cpu:16core, memory:16G",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system-cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "system-memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  { "title": "Altibase Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "nval02 UpTime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_basic_info",
     "select": [
      [
       { "params": [ "DB_UP_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval02 currentSession",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval02 DiskBuffHit",
   "type": "singlestat",
   "description": "Disk Buffer Hit 율",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval02 PlanCache Hit",
   "type": "singlestat",
   "description": "PlanCache Buffer Hit 율\n",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval02 Memory Used Ratio",
   "type": "gauge",
   "description": "MEM_MAX_DB_SIZE 대비 현재 메모리 space 사용량",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "Altibase있는 Filesystem Disk여유율(nval02)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 UpTime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_basic_info",
     "select": [
      [
       { "params": [ "DB_UP_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 currentSession",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 DiskBuffHit",
   "type": "singlestat",
   "description": "Disk Buffer Hit 율",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 PlanCache Hit",
   "type": "singlestat",
   "description": "PlanCache Buffer Hit 율\n",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 Memory Used Ratio",
   "type": "gauge",
   "description": "MEM_MAX_DB_SIZE 대비 현재 메모리 space 사용량",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "Altibase있는 Filesystem Disk여유율(nval03)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "Alti Process CPU usage",
   "type": "graph",
   "description": "Altibase Process 의 CPU 사용량 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "nval02",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "nval03",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "Alti Process Memory RSS Usage",
   "type": "graph",
   "description": "Altibase 메모리 사용량 추이\nRSS:실제 메모리가 세팅된 크기이고 스와핑이 되지 않은 물리적 메모리가 해당 task에 쓰이고 있는 양.\nVMS:가상 메모리의 크기이고,현재 디바이스 메핑에서는 제외 되어 있다는 의미.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "nval02",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "nval03",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "Alti Network TcpRecv usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "nval02-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "nval03-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Alti Network TcpSend usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "nval02-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "nval03-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "nval02 Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "nval02 Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "nval03 Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "prepare된 statement count",
   "type": "graph",
   "description": "Altibase 의 총 prepare 된 statement(SQL) 의 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "nval02",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "query": "SELECT mean(\"VALUE\") FROM \"alti_sysstat\" WHERE (\"NAME\" = 'prepare success count' AND \"host\" = 'qar5') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "prepare success count" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "nval03",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "prepare success count" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  { "title": "Rep State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Sender status",
   "type": "singlestat",
   "description": "이중화 Sender Thread 의 현재 status 표시",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 65 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "alti_repsender_info",
     "query": "select STATUS from alti_repsender_info where host = 'nval03(senderclient)' order by time desc limit 1 ",
     "select": [
      [
       { "params": [ "STATUS" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" },
      { "condition": "AND", "key": "REP_NAME", "operator": "=", "value": "REP" }
     ]
    }
   ]
  },
  {
   "title": "Sender start",
   "type": "singlestat",
   "description": "이중화 Sender Thread의 start 여부 표시",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 65 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "alti_repsender_start_stat",
     "query": "select IS_STARTED from alti_reprecv_stat where host = 'nval03(senderclient)' order by time desc limit 1 ",
     "select": [
      [
       { "params": [ "REP_STATE" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" },
      { "condition": "AND", "key": "REPLICATION_NAME", "operator": "=", "value": "REP" }
     ]
    }
   ]
  },
  {
   "title": "Receiver start",
   "type": "singlestat",
   "description": "이중화 Receiver thread의 start 여부 표시",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 65 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "alti_reprecv_stat",
     "query": "select IS_STARTED from alti_reprecv_stat where host = 'nval02(receiver)' order by time desc limit 1 ",
     "select": [
      [
       { "params": [ "IS_STARTED" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "Replication Gap Start",
   "type": "graph",
   "description": "Replication Gap 의 변화 추이",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "REP",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repgap_stat",
     "select": [
      [
       { "params": [ "REP_GAP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(senderclient)" },
      { "condition": "AND", "key": "REP_NAME", "operator": "=", "value": "REP" }
     ]
    }
   ]
  },
  {
   "title": "Replication Sender DML Log stat",
   "type": "graph",
   "description": "이중화 Sender가 보낸 DML 종류별 count",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "REP(INSERT)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_log_stat",
     "select": [
      [
       { "params": [ "INSERT_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "REP(DELETE)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_log_stat",
     "select": [
      [
       { "params": [ "DELETE_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "REP(UPDATE)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_log_stat",
     "query": "SELECT mean(\"UPDATE_LOG_COUNT\") FROM \"alti_repsender_log_stat\" WHERE (\"host\" = 'nval03(sender,client)' AND \"host\" = 'nval03(sender,client)') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "UPDATE_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nval03(sender,client)" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "REP(LOB)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_log_stat",
     "select": [
      [
       { "params": [ "LOB_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "Receiver Error Count",
   "type": "graph",
   "description": "Replication Receiver 에서 적용시 발생한 ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "REP(INSERT FAIL)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_reprecv_stat",
     "select": [
      [
       { "params": [ "INSERT_FAILURE_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "REP(DELETE FAIL)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_reprecv_stat",
     "select": [
      [
       { "params": [ "DELETE_FAILURE_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "REP(UPDATE FAIL)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_reprecv_stat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "Receiver DML success count",
   "type": "graph",
   "description": "이중화 Sender가 보낸 DML 종류별 count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "REP(INSERT)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_reprecv_stat",
     "select": [
      [
       { "params": [ "INSERT_SUCCESS_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "REP(UPDATE)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_reprecv_stat",
     "select": [
      [
       { "params": [ "UPDATE_SUCCESS_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    },
    {
     "alias": "REP(DELETE)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_reprecv_stat",
     "select": [
      [
       { "params": [ "DELETE_SUCCESS_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REPLICATION_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval02(receiver)" }
     ]
    }
   ]
  },
  {
   "title": "Rep Sender Log Count",
   "type": "graph",
   "description": "이중화 Sender 가 읽고 전송한 로그 count ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "REP(READ LOG)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_info",
     "select": [
      [
       { "params": [ "READ_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "REP(SENDER LOG)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_info",
     "select": [
      [
       { "params": [ "SEND_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  },
  {
   "title": "Rep Sender table Log count",
   "type": "graph",
   "description": "이중화 sender가 전송한 table 별 DML 종류별 count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "REP(TB_TEST1:INSERT)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_tblog_stat",
     "select": [
      [
       { "params": [ "INSERT_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" },
      { "condition": "AND", "key": "TABLE_NAME", "operator": "=", "value": "TB_TEST1" }
     ]
    },
    {
     "alias": "REP(TB_TEST1:UPDATE)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_tblog_stat",
     "select": [
      [
       { "params": [ "UPDATE_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "TABLE_NAME", "operator": "=", "value": "TB_TEST1" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    },
    {
     "alias": "REP(TB_TEST1:DELETE)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_repsender_tblog_stat",
     "select": [
      [
       { "params": [ "DELETE_LOG_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "REP_NAME", "operator": "=", "value": "REP" },
      { "condition": "AND", "key": "TABLE_NAME", "operator": "=", "value": "TB_TEST1" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nval03(senderclient)" }
     ]
    }
   ]
  }
 ]
}