{
 "title": "sd01",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU(sharding node1,2,3,4)",
   "type": "graph",
   "description": "node1:cpu cores : 8, memory:256Gbyte\nnode2:cpu cores : 8, memory:256Gbyte\nnode3:cpu cores : 8, memory:256Gbyte\nnode4:cpu cores : 8, memory:252Gbyte",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "cpu(node1(105))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "cpu(node2(106))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "cpu(node3(107))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "cpu(node4(108))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "System Memory(sharding node1,2,3,4)",
   "type": "graph",
   "description": "node1:cpu cores : 8, memory:256Gbyte\nnode2:cpu cores : 8, memory:256Gbyte\nnode3:cpu cores : 8, memory:256Gbyte\nnode4:cpu cores : 8, memory:252Gbyte",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mem(node1(105))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "mem(node2(106))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "mem(node3(107))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "mem(node4(108))",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "System/CPU/Memory(node1(105))",
   "type": "graph",
   "description": "node1:cpu cores : 8, memory:256Gbyte\nnode2:cpu cores : 8, memory:256Gbyte\nnode3:cpu cores : 8, memory:256Gbyte\nnode4:cpu cores : 8, memory:252Gbyte",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system-cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "system-memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    }
   ]
  },
  {
   "title": "System/CPU/Memory(node2(106))",
   "type": "graph",
   "description": "node1:cpu cores : 8, memory:256Gbyte\nnode2:cpu cores : 8, memory:256Gbyte\nnode3:cpu cores : 8, memory:256Gbyte\nnode4:cpu cores : 8, memory:252Gbyte",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system-cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "system-memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    }
   ]
  },
  {
   "title": "System/CPU/Memory(node3(107))",
   "type": "graph",
   "description": "node1:cpu cores : 8, memory:256Gbyte\nnode2:cpu cores : 8, memory:256Gbyte\nnode3:cpu cores : 8, memory:256Gbyte\nnode4:cpu cores : 8, memory:252Gbyte",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system-cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "system-memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    }
   ]
  },
  {
   "title": "System/CPU/Memory(node4(108))",
   "type": "graph",
   "description": "node1:cpu cores : 8, memory:256Gbyte\nnode2:cpu cores : 8, memory:256Gbyte\nnode3:cpu cores : 8, memory:256Gbyte\nnode4:cpu cores : 8, memory:252Gbyte",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system-cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    },
    {
     "alias": "system-memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  { "title": "Altibase Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Altibase있는 Filesystem Disk여유율(node1)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "LOG_DIR" }
     ]
    }
   ]
  },
  {
   "title": "Altibase있는 Filesystem Disk여유율(node2)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "LOG_DIR" }
     ]
    }
   ]
  },
  {
   "title": "Altibase있는 Filesystem Disk여유율(node3)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "LOG_DIR" }
     ]
    }
   ]
  },
  {
   "title": "Altibase있는 Filesystem Disk여유율(node4)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_diskusage_mycollector",
     "select": [
      [
       { "params": [ "useratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "LOG_DIR" }
     ]
    }
   ]
  },
  {
   "title": "currentSession",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "DiskBuffHit",
   "type": "graph",
   "description": "Disk Buffer Hit 율",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_buffhit_stat",
     "select": [
      [
       { "params": [ "HIT_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "PlanCache Hit",
   "type": "graph",
   "description": "PlanCache Buffer Hit 율\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_plancache_stat",
     "select": [
      [
       { "params": [ "CACHE_MISS_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used Ratio",
   "type": "graph",
   "description": "MEM_MAX_DB_SIZE 대비 현재 메모리 space 사용량",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_mem_stat",
     "select": [
      [
       { "params": [ "MEM_USED_RATIO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "Alti Process CPU usage",
   "type": "graph",
   "description": "Altibase Process 의 CPU 사용량 추이",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    }
   ]
  },
  {
   "title": "Alti Process Memory RSS Usage",
   "type": "graph",
   "description": "Altibase 메모리 사용량 추이\nRSS:실제 메모리가 세팅된 크기이고 스와핑이 되지 않은 물리적 메모리가 해당 task에 쓰이고 있는 양.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "altibase" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "altibase" }
     ]
    }
   ]
  },
  {
   "title": "node1 Alti Network usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TcpRecv-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpSend-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpRecv-eth5",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth5" }
     ]
    },
    {
     "alias": "TcpSend-eth5",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth5" }
     ]
    }
   ]
  },
  {
   "title": "node2 Alti Network usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TcpRecv-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpSend-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpRecv-eth4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    },
    {
     "alias": "TcpSend-eth4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    }
   ]
  },
  {
   "title": "node3 Alti Network usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TcpRecv-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpSend-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpRecv-eth3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth3" }
     ]
    },
    {
     "alias": "TcpSend-eth3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth3" }
     ]
    }
   ]
  },
  {
   "title": "node4 Alti Network usage",
   "type": "graph",
   "description": "Altibase 의 초당 Network 사용량 추이",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TcpRecv-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpSend-eth0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "TcpRecv-eth4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    },
    {
     "alias": "TcpSend-eth4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    }
   ]
  },
  {
   "title": "node1 Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    }
   ]
  },
  {
   "title": "node2 Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    }
   ]
  },
  {
   "title": "node3 Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    }
   ]
  },
  {
   "title": "node4 Connections",
   "type": "graph",
   "description": "Altibase Connection 수 추이\n총 접속 및 현재 실행중인 session 수 구분 표시",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "current session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "CURRENT_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    },
    {
     "alias": "executing session",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "EXEC_SESSION_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    },
    {
     "alias": "statement cnt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_session_stat",
     "select": [
      [
       { "params": [ "STATEMENT_CNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "node1 Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    }
   ]
  },
  {
   "title": "node2 Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" }
     ]
    }
   ]
  },
  {
   "title": "node3 Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    }
   ]
  },
  {
   "title": "node4 Service Thread",
   "type": "graph",
   "description": "Altibase Service Thread 개수 추이",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    },
    {
     "alias": "Executing",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "altibase_srv_stat",
     "select": [
      [
       { "params": [ "EXECUTE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" }
     ]
    }
   ]
  },
  {
   "title": "prepare된 statement count",
   "type": "graph",
   "description": "Altibase 의 총 prepare 된 statement(SQL) 의 개수 추이",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "node1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "prepare success count" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "node1(105)" }
     ]
    },
    {
     "alias": "node2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node2(106)" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "prepare success count" }
     ]
    },
    {
     "alias": "node3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "NAME", "operator": "=", "value": "prepare success count" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "node3(107)" }
     ]
    },
    {
     "alias": "node4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alti_sysstat",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "node4(108)" },
      { "condition": "AND", "key": "NAME", "operator": "=", "value": "prepare success count" }
     ]
    }
   ]
  }
 ]
}